// <auto-generated />
using System;
using DigitalAllianceTogo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DigitalAllianceTogo.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260923165906_Notifications")]
    partial class Notifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Audit.JournalAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("AdresseIP")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("AncienneValeur")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateAction")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Entite")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("EntiteId")
                        .HasColumnType("uuid");

                    b.Property<string>("NouvelleValeur")
                        .HasColumnType("text");

                    b.Property<Guid?>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DateAction");

                    b.HasIndex("UtilisateurId");

                    b.HasIndex("Entite", "EntiteId");

                    b.ToTable("JournauxAudit", (string)null);
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Catalogue.AttributProduit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProduitId")
                        .HasColumnType("uuid");

                    b.Property<string>("Valeur")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProduitId");

                    b.ToTable("AttributsProduit", (string)null);
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Catalogue.Categorie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Catalogue.ImageProduit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("EstPrincipale")
                        .HasColumnType("boolean");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProduitId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ProduitId");

                    b.ToTable("ImagesProduit", (string)null);
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Catalogue.Marque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Marques", (string)null);
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Catalogue.Produit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CategorieId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("MarqueId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Prix")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.HasIndex("MarqueId");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("Produits", (string)null);
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Commande.AdresseLivraisonCommande", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("CommandeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Ligne1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Ligne2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Pays")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TelephoneContact")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CommandeId")
                        .IsUnique();

                    b.ToTable("AdressesLivraisonCommande", (string)null);
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Commande.Commande", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DevisOrigineId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("VersionActive")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DevisOrigineId");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("Statut");

                    b.ToTable("Commandes", (string)null);
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Commande.LigneCommande", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("PrixUnitaire")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ProduitId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer");

                    b.Property<decimal>("Remise")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("VersionCommandeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProduitId");

                    b.HasIndex("VersionCommandeId");

                    b.ToTable("LignesCommande", (string)null);
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Commande.VersionCommande", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CommandeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreeParId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateReponse")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MotifModification")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("MotifRefus")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("NumeroVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Regularisation")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("Remise")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("SousTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("ValideParId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Statut");

                    b.HasIndex("CommandeId", "NumeroVersion")
                        .IsUnique();

                    b.ToTable("VersionsCommande", (string)null);
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Devis.Devis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("CommentaireClient")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("CommentaireInterne")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("CreeParId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateValidation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateValidite")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Remise")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("SousTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("ValideParId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CreeParId");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("Statut");

                    b.HasIndex("ValideParId");

                    b.ToTable("Devis", (string)null);
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Devis.LigneDevis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DevisId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PrixUnitaire")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ProduitId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer");

                    b.Property<decimal>("Remise")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DevisId");

                    b.HasIndex("ProduitId");

                    b.ToTable("LignesDevis", (string)null);
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Finance.Avoir", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommandeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateUtilisation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Montant")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("MontantUtilise")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("TicketSAVId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("VersionCommandeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CommandeId");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("TicketSAVId");

                    b.HasIndex("VersionCommandeId");

                    b.ToTable("Avoirs", (string)null);
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Finance.Paiement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AvoirId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommandeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConfirmeParId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DateConfirmation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DatePaiement")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("Montant")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("MotifRejet")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PreuveUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ReferenceExterne")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("VersionCommandeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AvoirId");

                    b.HasIndex("CommandeId");

                    b.HasIndex("ConfirmeParId");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("ReferenceExterne");

                    b.HasIndex("VersionCommandeId");

                    b.HasIndex("Statut", "DateConfirmation");

                    b.ToTable("Paiements", (string)null);
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Finance.Remboursement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommandeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateDemande")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateExecution")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Montant")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MotifEchec")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ReferenceTransaction")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("TicketSAVId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VersionCommandeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CommandeId");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("TicketSAVId");

                    b.HasIndex("VersionCommandeId");

                    b.ToTable("Remboursements", (string)null);
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Livraison.Livraison", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommandeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DateLivraison")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DatePlanifiee")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DatePriseEnCharge")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LivreurId")
                        .HasColumnType("uuid");

                    b.Property<string>("MotifEchec")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Reserve")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("TicketSAVId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("CommandeId");

                    b.HasIndex("LivreurId");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("Statut");

                    b.HasIndex("TicketSAVId");

                    b.ToTable("Livraisons", (string)null);
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Livraison.PreuveLivraison", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Commentaire")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("DatePreuve")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<Guid>("LivraisonId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("SignatureUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("LivraisonId")
                        .IsUnique();

                    b.ToTable("PreuvesLivraison", (string)null);
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateEnvoiEmail")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateLecture")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErreurEmail")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Lien")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("StatutEmail")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TentativesEmail")
                        .HasColumnType("integer");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("StatutEmail");

                    b.HasIndex("ClientId", "DateCreation");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Panier.LignePanier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateAjout")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PanierId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PrixUnitaire")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ProduitId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProduitId");

                    b.HasIndex("PanierId", "ProduitId")
                        .IsUnique();

                    b.ToTable("LignesPanier", (string)null);
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Panier.Panier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Paniers", (string)null);
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Parametres.ParametresEntreprise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DelaiExpirationPaiementHeures")
                        .HasColumnType("integer");

                    b.Property<int>("DureeValiditeDevisJours")
                        .HasColumnType("integer");

                    b.Property<string>("NomBeneficiairePaiement")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NumeroFlooz")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("NumeroTMoney")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("SeuilAugmentationModificationPourcent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("SeuilRemiseCommercialPourcent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.ToTable("ParametresEntreprise", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5e1d7a3c-0b7e-4c1a-9a51-2f7c4d9e8a01"),
                            DateModification = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            DelaiExpirationPaiementHeures = 48,
                            DureeValiditeDevisJours = 15,
                            SeuilAugmentationModificationPourcent = 10m,
                            SeuilRemiseCommercialPourcent = 10m
                        });
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.SAV.Diagnostic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Conclusion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("DateDiagnostic")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Recommandation")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("Reparable")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TechnicienId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TicketSAVId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TechnicienId");

                    b.HasIndex("TicketSAVId");

                    b.ToTable("Diagnostics", (string)null);
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.SAV.Intervention", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Resultat")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("TechnicienId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TicketSAVId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TechnicienId");

                    b.HasIndex("TicketSAVId");

                    b.ToTable("Interventions", (string)null);
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.SAV.TicketSAV", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AncienProduitReceptionne")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DateCloture")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Decision")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("LigneCommandeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Resolution")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("TechnicienId")
                        .HasColumnType("uuid");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("LigneCommandeId");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("Statut");

                    b.HasIndex("TechnicienId");

                    b.ToTable("TicketsSAV", (string)null);
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Security.Adresse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("CodePostal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ligne1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Ligne2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Pays")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Adresses", (string)null);
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Security.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodeClient")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Prenom")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RaisonSociale")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid?>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CodeClient")
                        .IsUnique();

                    b.HasIndex("Telephone");

                    b.HasIndex("UtilisateurId")
                        .IsUnique();

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Security.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Permissions", (string)null);
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Security.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Security.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Security.Utilisateur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Utilisateurs", (string)null);
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Security.UtilisateurRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateAffectation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UtilisateurId", "RoleId")
                        .IsUnique();

                    b.ToTable("UtilisateurRoles", (string)null);
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Stock.EcartReception", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConstateParId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateConstat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDecision")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DecideParId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EntrepotId")
                        .HasColumnType("uuid");

                    b.Property<string>("MotifDecision")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ProduitId")
                        .HasColumnType("uuid");

                    b.Property<int>("QuantiteCommandee")
                        .HasColumnType("integer");

                    b.Property<int>("QuantiteRecue")
                        .HasColumnType("integer");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("EntrepotId");

                    b.HasIndex("ProduitId");

                    b.HasIndex("Statut");

                    b.ToTable("EcartsReception", (string)null);
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Stock.Entrepot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Actif")
                        .HasColumnType("boolean");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("Entrepots", (string)null);
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Stock.MouvementStock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CommandeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateMouvement")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("StockProduitId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TicketSAVId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("CommandeId");

                    b.HasIndex("StockProduitId");

                    b.HasIndex("TicketSAVId");

                    b.ToTable("MouvementsStock", (string)null);
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Stock.StockProduit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EntrepotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProduitId")
                        .HasColumnType("uuid");

                    b.Property<int>("QuantiteDefectueuse")
                        .HasColumnType("integer");

                    b.Property<int>("QuantiteEnTransit")
                        .HasColumnType("integer");

                    b.Property<int>("QuantitePhysique")
                        .HasColumnType("integer");

                    b.Property<int>("QuantiteReservee")
                        .HasColumnType("integer");

                    b.Property<int>("SeuilAlerte")
                        .HasColumnType("integer");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ProduitId");

                    b.HasIndex("EntrepotId", "ProduitId")
                        .IsUnique();

                    b.ToTable("StocksProduit", (string)null);
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Audit.JournalAudit", b =>
                {
                    b.HasOne("DigitalAllianceTogo.Domain.Models.Security.Utilisateur", "Utilisateur")
                        .WithMany("JournauxAudit")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Catalogue.AttributProduit", b =>
                {
                    b.HasOne("DigitalAllianceTogo.Domain.Models.Catalogue.Produit", "Produit")
                        .WithMany("Attributs")
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Catalogue.ImageProduit", b =>
                {
                    b.HasOne("DigitalAllianceTogo.Domain.Models.Catalogue.Produit", "Produit")
                        .WithMany("Images")
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Catalogue.Produit", b =>
                {
                    b.HasOne("DigitalAllianceTogo.Domain.Models.Catalogue.Categorie", "Categorie")
                        .WithMany("Produits")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DigitalAllianceTogo.Domain.Models.Catalogue.Marque", "Marque")
                        .WithMany("Produits")
                        .HasForeignKey("MarqueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categorie");

                    b.Navigation("Marque");
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Commande.AdresseLivraisonCommande", b =>
                {
                    b.HasOne("DigitalAllianceTogo.Domain.Models.Commande.Commande", "Commande")
                        .WithOne("AdresseLivraison")
                        .HasForeignKey("DigitalAllianceTogo.Domain.Models.Commande.AdresseLivraisonCommande", "CommandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commande");
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Commande.Commande", b =>
                {
                    b.HasOne("DigitalAllianceTogo.Domain.Models.Security.Client", "Client")
                        .WithMany("Commandes")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DigitalAllianceTogo.Domain.Models.Devis.Devis", "DevisOrigine")
                        .WithMany("CommandesOrigine")
                        .HasForeignKey("DevisOrigineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");

                    b.Navigation("DevisOrigine");
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Commande.LigneCommande", b =>
                {
                    b.HasOne("DigitalAllianceTogo.Domain.Models.Catalogue.Produit", "Produit")
                        .WithMany("LignesCommande")
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DigitalAllianceTogo.Domain.Models.Commande.VersionCommande", "VersionCommande")
                        .WithMany("Lignes")
                        .HasForeignKey("VersionCommandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produit");

                    b.Navigation("VersionCommande");
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Commande.VersionCommande", b =>
                {
                    b.HasOne("DigitalAllianceTogo.Domain.Models.Commande.Commande", "Commande")
                        .WithMany("Versions")
                        .HasForeignKey("CommandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commande");
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Devis.Devis", b =>
                {
                    b.HasOne("DigitalAllianceTogo.Domain.Models.Security.Client", "Client")
                        .WithMany("Devis")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DigitalAllianceTogo.Domain.Models.Security.Utilisateur", "CreePar")
                        .WithMany()
                        .HasForeignKey("CreeParId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DigitalAllianceTogo.Domain.Models.Security.Utilisateur", "ValidePar")
                        .WithMany()
                        .HasForeignKey("ValideParId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Client");

                    b.Navigation("CreePar");

                    b.Navigation("ValidePar");
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Devis.LigneDevis", b =>
                {
                    b.HasOne("DigitalAllianceTogo.Domain.Models.Devis.Devis", "Devis")
                        .WithMany("Lignes")
                        .HasForeignKey("DevisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalAllianceTogo.Domain.Models.Catalogue.Produit", "Produit")
                        .WithMany("LignesDevis")
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Devis");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Finance.Avoir", b =>
                {
                    b.HasOne("DigitalAllianceTogo.Domain.Models.Commande.Commande", "Commande")
                        .WithMany("Avoirs")
                        .HasForeignKey("CommandeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DigitalAllianceTogo.Domain.Models.SAV.TicketSAV", "TicketSAV")
                        .WithMany()
                        .HasForeignKey("TicketSAVId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DigitalAllianceTogo.Domain.Models.Commande.VersionCommande", "VersionCommande")
                        .WithMany("AvoirsConcernes")
                        .HasForeignKey("VersionCommandeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Commande");

                    b.Navigation("TicketSAV");

                    b.Navigation("VersionCommande");
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Finance.Paiement", b =>
                {
                    b.HasOne("DigitalAllianceTogo.Domain.Models.Finance.Avoir", "Avoir")
                        .WithMany()
                        .HasForeignKey("AvoirId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DigitalAllianceTogo.Domain.Models.Commande.Commande", "Commande")
                        .WithMany("Paiements")
                        .HasForeignKey("CommandeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DigitalAllianceTogo.Domain.Models.Security.Utilisateur", "ConfirmePar")
                        .WithMany()
                        .HasForeignKey("ConfirmeParId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DigitalAllianceTogo.Domain.Models.Commande.VersionCommande", "VersionCommande")
                        .WithMany("PaiementsConcernes")
                        .HasForeignKey("VersionCommandeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Avoir");

                    b.Navigation("Commande");

                    b.Navigation("ConfirmePar");

                    b.Navigation("VersionCommande");
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Finance.Remboursement", b =>
                {
                    b.HasOne("DigitalAllianceTogo.Domain.Models.Commande.Commande", "Commande")
                        .WithMany("Remboursements")
                        .HasForeignKey("CommandeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DigitalAllianceTogo.Domain.Models.SAV.TicketSAV", "TicketSAV")
                        .WithMany()
                        .HasForeignKey("TicketSAVId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DigitalAllianceTogo.Domain.Models.Commande.VersionCommande", "VersionCommande")
                        .WithMany("RemboursementsConcernes")
                        .HasForeignKey("VersionCommandeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Commande");

                    b.Navigation("TicketSAV");

                    b.Navigation("VersionCommande");
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Livraison.Livraison", b =>
                {
                    b.HasOne("DigitalAllianceTogo.Domain.Models.Commande.Commande", "Commande")
                        .WithMany("Livraisons")
                        .HasForeignKey("CommandeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DigitalAllianceTogo.Domain.Models.Security.Utilisateur", "Livreur")
                        .WithMany("LivraisonsEnTantQueLivreur")
                        .HasForeignKey("LivreurId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DigitalAllianceTogo.Domain.Models.SAV.TicketSAV", "TicketSAV")
                        .WithMany()
                        .HasForeignKey("TicketSAVId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Commande");

                    b.Navigation("Livreur");

                    b.Navigation("TicketSAV");
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Livraison.PreuveLivraison", b =>
                {
                    b.HasOne("DigitalAllianceTogo.Domain.Models.Livraison.Livraison", "Livraison")
                        .WithOne("Preuve")
                        .HasForeignKey("DigitalAllianceTogo.Domain.Models.Livraison.PreuveLivraison", "LivraisonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livraison");
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Notifications.Notification", b =>
                {
                    b.HasOne("DigitalAllianceTogo.Domain.Models.Security.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Panier.LignePanier", b =>
                {
                    b.HasOne("DigitalAllianceTogo.Domain.Models.Panier.Panier", "Panier")
                        .WithMany("Lignes")
                        .HasForeignKey("PanierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalAllianceTogo.Domain.Models.Catalogue.Produit", "Produit")
                        .WithMany("LignesPanier")
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Panier");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Panier.Panier", b =>
                {
                    b.HasOne("DigitalAllianceTogo.Domain.Models.Security.Utilisateur", "Utilisateur")
                        .WithMany("Paniers")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.SAV.Diagnostic", b =>
                {
                    b.HasOne("DigitalAllianceTogo.Domain.Models.Security.Utilisateur", "Technicien")
                        .WithMany("DiagnosticsEnTantQueTechnicien")
                        .HasForeignKey("TechnicienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DigitalAllianceTogo.Domain.Models.SAV.TicketSAV", "TicketSAV")
                        .WithMany("Diagnostics")
                        .HasForeignKey("TicketSAVId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Technicien");

                    b.Navigation("TicketSAV");
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.SAV.Intervention", b =>
                {
                    b.HasOne("DigitalAllianceTogo.Domain.Models.Security.Utilisateur", "Technicien")
                        .WithMany("InterventionsEnTantQueTechnicien")
                        .HasForeignKey("TechnicienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DigitalAllianceTogo.Domain.Models.SAV.TicketSAV", "TicketSAV")
                        .WithMany("Interventions")
                        .HasForeignKey("TicketSAVId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Technicien");

                    b.Navigation("TicketSAV");
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.SAV.TicketSAV", b =>
                {
                    b.HasOne("DigitalAllianceTogo.Domain.Models.Security.Client", "Client")
                        .WithMany("TicketsSAV")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DigitalAllianceTogo.Domain.Models.Commande.LigneCommande", "LigneCommande")
                        .WithMany("TicketsSAV")
                        .HasForeignKey("LigneCommandeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DigitalAllianceTogo.Domain.Models.Security.Utilisateur", "Technicien")
                        .WithMany()
                        .HasForeignKey("TechnicienId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");

                    b.Navigation("LigneCommande");

                    b.Navigation("Technicien");
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Security.Adresse", b =>
                {
                    b.HasOne("DigitalAllianceTogo.Domain.Models.Security.Client", "Client")
                        .WithMany("Adresses")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Security.Client", b =>
                {
                    b.HasOne("DigitalAllianceTogo.Domain.Models.Security.Utilisateur", "Utilisateur")
                        .WithOne("Client")
                        .HasForeignKey("DigitalAllianceTogo.Domain.Models.Security.Client", "UtilisateurId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Security.RolePermission", b =>
                {
                    b.HasOne("DigitalAllianceTogo.Domain.Models.Security.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalAllianceTogo.Domain.Models.Security.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Security.UtilisateurRole", b =>
                {
                    b.HasOne("DigitalAllianceTogo.Domain.Models.Security.Role", "Role")
                        .WithMany("UtilisateurRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalAllianceTogo.Domain.Models.Security.Utilisateur", "Utilisateur")
                        .WithMany("UtilisateurRoles")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Stock.EcartReception", b =>
                {
                    b.HasOne("DigitalAllianceTogo.Domain.Models.Stock.Entrepot", "Entrepot")
                        .WithMany()
                        .HasForeignKey("EntrepotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DigitalAllianceTogo.Domain.Models.Catalogue.Produit", "Produit")
                        .WithMany()
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entrepot");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Stock.MouvementStock", b =>
                {
                    b.HasOne("DigitalAllianceTogo.Domain.Models.Commande.Commande", "Commande")
                        .WithMany()
                        .HasForeignKey("CommandeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DigitalAllianceTogo.Domain.Models.Stock.StockProduit", "StockProduit")
                        .WithMany("Mouvements")
                        .HasForeignKey("StockProduitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalAllianceTogo.Domain.Models.SAV.TicketSAV", "TicketSAV")
                        .WithMany()
                        .HasForeignKey("TicketSAVId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Commande");

                    b.Navigation("StockProduit");

                    b.Navigation("TicketSAV");
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Stock.StockProduit", b =>
                {
                    b.HasOne("DigitalAllianceTogo.Domain.Models.Stock.Entrepot", "Entrepot")
                        .WithMany("Stocks")
                        .HasForeignKey("EntrepotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DigitalAllianceTogo.Domain.Models.Catalogue.Produit", "Produit")
                        .WithMany("Stocks")
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entrepot");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Catalogue.Categorie", b =>
                {
                    b.Navigation("Produits");
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Catalogue.Marque", b =>
                {
                    b.Navigation("Produits");
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Catalogue.Produit", b =>
                {
                    b.Navigation("Attributs");

                    b.Navigation("Images");

                    b.Navigation("LignesCommande");

                    b.Navigation("LignesDevis");

                    b.Navigation("LignesPanier");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Commande.Commande", b =>
                {
                    b.Navigation("AdresseLivraison")
                        .IsRequired();

                    b.Navigation("Avoirs");

                    b.Navigation("Livraisons");

                    b.Navigation("Paiements");

                    b.Navigation("Remboursements");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Commande.LigneCommande", b =>
                {
                    b.Navigation("TicketsSAV");
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Commande.VersionCommande", b =>
                {
                    b.Navigation("AvoirsConcernes");

                    b.Navigation("Lignes");

                    b.Navigation("PaiementsConcernes");

                    b.Navigation("RemboursementsConcernes");
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Devis.Devis", b =>
                {
                    b.Navigation("CommandesOrigine");

                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Livraison.Livraison", b =>
                {
                    b.Navigation("Preuve");
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Panier.Panier", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.SAV.TicketSAV", b =>
                {
                    b.Navigation("Diagnostics");

                    b.Navigation("Interventions");
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Security.Client", b =>
                {
                    b.Navigation("Adresses");

                    b.Navigation("Commandes");

                    b.Navigation("Devis");

                    b.Navigation("TicketsSAV");
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Security.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Security.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UtilisateurRoles");
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Security.Utilisateur", b =>
                {
                    b.Navigation("Client");

                    b.Navigation("DiagnosticsEnTantQueTechnicien");

                    b.Navigation("InterventionsEnTantQueTechnicien");

                    b.Navigation("JournauxAudit");

                    b.Navigation("LivraisonsEnTantQueLivreur");

                    b.Navigation("Paniers");

                    b.Navigation("UtilisateurRoles");
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Stock.Entrepot", b =>
                {
                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("DigitalAllianceTogo.Domain.Models.Stock.StockProduit", b =>
                {
                    b.Navigation("Mouvements");
                });
#pragma warning restore 612, 618
        }
    }
}
